### ISSUE TITLE
Check ESlint rules

### ISSUE THREAD

**Issue by 2fd** [decentraland/decentraland-gatsby#303]
turn on:

- [x] `import/export`
- [x] `no-case-declarations`
- [x] `import/no-named-export`
- [x] `import/no-named-as-default`
- [ ] `import/no-named-as-default-member`
- [x] `@typescript-eslint/ban-types`
- [x] `@typescript-eslint/no-unused-vars`
- [x] `@typescript-eslint/no-var-requires`
- [ ] `@typescript-eslint/no-explicit-any`
- [ ] `@typescript-eslint/no-empty-function`
- [ ] `@typescript-eslint/explicit-module-boundary-types`
- [ ] `@typescript-eslint/no-non-null-assertion`
- [x] `@typescript-eslint/no-this-alias`

add:

- [x] `no-restricted-imports`
  - `lodash`
  - `decentraland-ui`
  - `decentraland-dapps`
  - `decentraland-connect`
  - `decentraland-gatsby`
  - `semantic-ui-react`
  - `@dcl/schemas`

**Comment by braianj** [comment]
The pending rules were turned off and for the time being will remain as follows
